name: ✨ Feature Request
description: Suggest a new feature for the Git Blame extension
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your feature request! We appreciate your ideas for improving the Git Blame extension.
  
  - type: checkboxes
    id: prior-search
    attributes:
      label: Have you searched for existing feature requests?
      options:
        - label: I have searched existing issues
          required: true
  
  - type: input
    id: feature-summary
    attributes:
      label: Feature Summary
      description: Brief description of the feature
      placeholder: "e.g., Add keyboard shortcut to toggle git blame overlay"
    validations:
      required: true
  
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What workflow would it improve?
      placeholder: |
        Currently, when I'm reviewing code, I need to...
        This is inconvenient because...
        It would be better if...
    validations:
      required: true
  
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this feature work? Describe the desired behavior and user experience.
      placeholder: |
        The feature should work like this:
        1. User presses Ctrl+Shift+B...
        2. The overlay toggles...
        3. User sees...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other approaches or workarounds?
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...
        - Current workaround: ...
      render: markdown
    validations:
      required: false
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve workflow
        - High - Critical for my use case
    validations:
      required: true
  
  - type: checkboxes
    id: components
    attributes:
      label: Affected Areas
      description: Which parts of the extension does this relate to?
      options:
        - label: Git blame overlay display
        - label: Hover tooltip functionality
        - label: Status bar integration
        - label: Commands and keyboard shortcuts
        - label: Configuration/settings
        - label: Performance
        - label: Documentation
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, examples from other extensions, or other relevant information
      placeholder: "Include any additional details, mockups, or references here..."
    validations:
      required: false
